//Get HTTP Post 
//Clients
Get http://localhost:3000/database/clients

//Get Clients by ID
GET http://localhost:3000/database/clients/67997ca27641a22bc7b008d4

//Cars
Get http://localhost:3000/database/cars

//Cars by ID
Get http://localhost:3000/database/cars/67959d10f49df630cef3c90c


//Create HTTP Post
//Clients
POST http://localhost:3000/database/clients HTTP/1.1
Content-Type: application/json

{
    "PrincipalName": "Jeimy",
    "LastName": "Alvarado",
    "License": "Red",
    "Age": "24",
    "Birthday": "2000-05-05T00:00:00.000Z",
    "Country": "Guatemala",
    "Cars": [
        "Nissan",
        "Honda",
        "KIA"
    ]
}

//Cars
POST http://localhost:3000/database/cars HTTP/1.1
Content-Type: application/json

{
    "Car": "Changan",
    "Year": 2025,
    "Colors": [
        "red",
        "yellow",
        "gold",
        "white"
    ],
    "Price": 100000,
    "Currency": "dolar"
}

//Update HTTP Put
//Clients
PUT http://localhost:3000/database/clients/67997ca27641a22bc7b008d4 HTTP/1.1
Content-Type: application/json

{
    "PrincipalName": "Rubi",
    "LastName": "Alvarado",
    "License": "Platinum",
    "Age": "24",
    "Birthday": "2000-05-05T00:00:00.000Z",
    "Country": "Guatemala",
    "Cars": [
        "Toyota",
        "Nissan",
        "Honda",
        "Mazda"
    ]
}

//Cars
PUT http://localhost:3000/database/cars/6795bce66aa2fe7226903801 HTTP/1.1
Content-Type: application/json

{
    "Car": "Changan",
    "Year": 2024,
    "Colors": [
        "red",
        "yellow"
    ],
    "Price": 100000,
    "Currency": "dolar"
}

//Delete HTTP Delete
//Clients
DELETE http://localhost:3000/database/clients/67997ca27641a22bc7b008d4

//Cars
DELETE http://localhost:3000/database/cars/6795bce66aa2fe7226903801